language: java
deploy:
  provider: releases
  api_key:
    secure: Rgb/NMcsAohpjPtZnpRfCODzRg0jECIxYMdPTG0J1g8h53ulZUPcWrmsPqRC/WSxaA/hBzLuogblquAzLPn3u+LM0hFb7rIapIz/vBaHfKOHT3up2Q8sR008wlIpmH+syR1rjOyXeZ+2gi7JnxfGMrUO8oW4l8E9TT30oulnogRF6H+MvlFdOrBxk27PyBgAfyXbWnrM5qNqEBMoN7OmWlsVIHjq5yY5G6K0+RCf09vMnlNGfsesV2QZ7/lbZlc3EnWZMWNJLxpcoO6U2k3Xb15fJnLUkYz2SjielbgMkKnd2+VeVYSMLsV7TE3m0JYGdrV+tPOPGV4OUe/k0AKFcbk2tnpxX8aHA4ru7qFqWWLslF4TCIUlD5kseRTPeTHQR5PoZw+k+U/HyT7qkaN6e1CElp4SdyBfyFlWWHhbYHZjELOPnlqb4Ti9GsTudTQwTifnfzjRYoXyI5dAw2KjSqdLYc10VCXnu0w0l8Cu2D20A6miOf7VxnMNYBIPPCr91r5jjjDEW59ofAaVoGUInxgu/pEN5VXG81sIS7iHFGFzPuXPD+C5/usHQKml5Ef4d20tPxdKNjB/SY6971wAx9uXFw7SFcZmfWOop7mytpMIGppEYN/CxVm3mg3v9pjFQzvF1aqw3vXCASTss/mNxDaKK+SCZX9qzfsaGVo+97I=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-ext-plugin
