language: java
deploy:
  provider: releases
  api_key:
    secure: QGG5xT1y58Epc8tJvYKaCdymdMsOSQtJ7js7HuFJTXfzhlVNEhr0p0aP7y+Lncsa8bkCcUZ1dwhtZrbStMq/kdZ3PLuu7wVU4kkSU4FcmBnSwUdU/zp2Rje4VX18XaS7mk2In9k7f4P+y82jovhZ4QUQPwzR4sY7Frc3Tb9P0Nw9G0KiGu9/PMHJTS5eFXO6dO+ttEApQe2/Eg3IAidkA9VHu9uCHiZoHRjoVcYZKS8KwVOcv3Z1HehGOv12JHMxrFoeaf2Uk+SYp3A60Jl0nD8gDDz8QVJ3KfQ6mO3OeE9EU2kLq9CjyT60Ki7RZuK0uAA3+CuyaJEaDQEVlRv1i9Reg9cH538DjeWp0JSahykW/z2bELeLopcAvpBNd+tvFE40VEaEwhWbw68Hpx4yxbzAuly8VsQewH50CWILSl/aH11PeqmRD5xotHoTt2BwdJH4YjIXBwRM6u1UPLO2/bBGr3Ui3tX3mgFXtJO6wQ3WjMEoCo5JmOS7N7S+qSsMedbXNc0cRVZx824vLQXa+jFlwg6EsiqZjrPd9Azkub/aaMH9tYdRUo0sufRXL1Hxpw9GsrpfNipozu8vLXugTXV1zOcpV1vTdVW77rqmg/nVw4MED2d5lz8I23fNXZKKFTLTdzI+ya6b+QKa9QhO92qRbEpEQSXxt6GckgO2qM0=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-ext-plugin
